name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: E2E on chrome
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run Cypress tests using Google Chrome
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          browser: chrome
          build: npm run build
          start: npm start